/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as WaiversRouteImport } from './routes/waivers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiversRoute = WaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/schedule': typeof ScheduleRoute
  '/waivers': typeof WaiversRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/schedule': typeof ScheduleRoute
  '/waivers': typeof WaiversRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matchup': typeof MatchupRoute
  '/schedule': typeof ScheduleRoute
  '/waivers': typeof WaiversRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matchup' | '/schedule' | '/waivers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matchup' | '/schedule' | '/waivers'
  id: '__root__' | '/' | '/matchup' | '/schedule' | '/waivers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchupRoute: typeof MatchupRoute
  ScheduleRoute: typeof ScheduleRoute
  WaiversRoute: typeof WaiversRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waivers': {
      id: '/waivers'
      path: '/waivers'
      fullPath: '/waivers'
      preLoaderRoute: typeof WaiversRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchupRoute: MatchupRoute,
  ScheduleRoute: ScheduleRoute,
  WaiversRoute: WaiversRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
